<?php die( 'These aren\'t the droids you\'re looking for...' );
// an extract of translatable text strings from the static config array
_x( 'Advanced', 'lib file description', 'nextgen-facebook' );
_x( 'All Options', 'form option value', 'nextgen-facebook' );
_x( 'Basic Options', 'form option value', 'nextgen-facebook' );
_x( 'Bit.ly', 'form option value', 'nextgen-facebook' );
_x( 'Bottom', 'form option value', 'nextgen-facebook' );
_x( 'Center', 'form option value', 'nextgen-facebook' );
_x( '(default)', 'form option value', 'nextgen-facebook' );
_x( 'Default value', 'form option value', 'nextgen-facebook' );
_x( 'Display Name', 'form option value', 'nextgen-facebook' );
_x( 'Display your content in the best possible way on Facebook, Google+, Twitter, Pinterest, etc. - no matter how your webpage is shared!', 'plugin description', 'nextgen-facebook' );
_x( 'Excerpt Only', 'form option value', 'nextgen-facebook' );
_x( 'First and Last Names', 'form option value', 'nextgen-facebook' );
_x( 'Footer', 'form option value', 'nextgen-facebook' );
_x( 'Force this value', 'form option value', 'nextgen-facebook' );
_x( 'General', 'lib file description', 'nextgen-facebook' );
_x( 'Goo.gl', 'form option value', 'nextgen-facebook' );
_x( 'Header', 'form option value', 'nextgen-facebook' );
_x( 'If value is empty', 'form option value', 'nextgen-facebook' );
_x( 'Left', 'form option value', 'nextgen-facebook' );
_x( 'Nickname', 'form option value', 'nextgen-facebook' );
_x( 'No', 'form option value', 'nextgen-facebook' );
_x( '(no images)', 'form option value', 'nextgen-facebook' );
_x( '[none]', 'form option value', 'nextgen-facebook' );
_x( '(no videos)', 'form option value', 'nextgen-facebook' );
_x( '(option disabled)', 'form option value', 'nextgen-facebook' );
_x( 'Read Me', 'lib file description', 'nextgen-facebook' );
_x( 'Right', 'form option value', 'nextgen-facebook' );
_x( '(settings value)', 'form option value', 'nextgen-facebook' );
_x( 'Setup Guide', 'lib file description', 'nextgen-facebook' );
_x( 'Sharing Buttons', 'lib file description', 'nextgen-facebook' );
_x( 'Sharing Styles', 'lib file description', 'nextgen-facebook' );
_x( 'Social Image Dimensions', 'lib file description', 'nextgen-facebook' );
_x( '<span>Extension Plugins</span> and Pro Licenses', 'lib file description', 'nextgen-facebook' );
_x( 'Title and Excerpt', 'form option value', 'nextgen-facebook' );
_x( 'Title Only', 'form option value', 'nextgen-facebook' );
_x( 'Top', 'form option value', 'nextgen-facebook' );
_x( 'Update Manager for the NextGEN Facebook (NGFB) Pro plugin and its Pro extensions.', 'plugin description', 'nextgen-facebook' );
_x( 'User Profile Contact Methods', 'lib file description', 'nextgen-facebook' );
_x( 'Website / Business Social Accounts', 'lib file description', 'nextgen-facebook' );
_x( 'Yes', 'form option value', 'nextgen-facebook' );
?>
