<?php die( 'These aren\'t the droids you\'re looking for...' );
// extract of translatable text strings from static config array(s)
_x( 'Admin Edit', 'metabox tab', 'nextgen-facebook' );
_x( 'Admin Edit', 'option value', 'nextgen-facebook' );
_x( 'Advanced Settings', 'lib file description', 'nextgen-facebook' );
_x( 'All Buttons', 'metabox tab', 'nextgen-facebook' );
_x( 'All Options', 'option value', 'nextgen-facebook' );
_x( 'Any Platform', 'option value', 'nextgen-facebook' );
_x( 'Basic Options', 'option value', 'nextgen-facebook' );
_x( 'Bit.ly (suggested)', 'option value', 'nextgen-facebook' );
_x( 'Bottom', 'option value', 'nextgen-facebook' );
_x( 'Center', 'option value', 'nextgen-facebook' );
_x( 'Content', 'metabox tab', 'nextgen-facebook' );
_x( 'Content', 'option value', 'nextgen-facebook' );
_x( 'CSS Sidebar', 'metabox tab', 'nextgen-facebook' );
_x( 'CSS Sidebar', 'option value', 'nextgen-facebook' );
_x( '(default)', 'option value', 'nextgen-facebook' );
_x( 'Desktop Only', 'option value', 'nextgen-facebook' );
_x( 'Display Name', 'option value', 'nextgen-facebook' );
_x( 'Display your content in the best possible way on Facebook, Google+, Twitter, Pinterest, etc. - no matter how your webpage is shared!', 'plugin description', 'nextgen-facebook' );
_x( 'Essential Settings', 'lib file description', 'nextgen-facebook' );
_x( 'Excerpt', 'metabox tab', 'nextgen-facebook' );
_x( 'Excerpt Only', 'option value', 'nextgen-facebook' );
_x( 'Excerpt', 'option value', 'nextgen-facebook' );
_x( 'First and Last Names', 'option value', 'nextgen-facebook' );
_x( 'Footer', 'option value', 'nextgen-facebook' );
_x( 'Force this value', 'option value', 'nextgen-facebook' );
_x( 'Friday', 'option value', 'nextgen-facebook' );
_x( 'General Settings', 'lib file description', 'nextgen-facebook' );
_x( 'Goo.gl', 'option value', 'nextgen-facebook' );
_x( 'Header', 'option value', 'nextgen-facebook' );
_x( '<highlight>Setup Guide</highlight>', 'lib file description', 'nextgen-facebook' );
_x( 'If value is empty', 'option value', 'nextgen-facebook' );
_x( 'Left', 'option value', 'nextgen-facebook' );
_x( 'Mobile Only', 'option value', 'nextgen-facebook' );
_x( 'Monday', 'option value', 'nextgen-facebook' );
_x( 'New activation', 'option value', 'nextgen-facebook' );
_x( 'Nickname', 'option value', 'nextgen-facebook' );
_x( '(no images)', 'option value', 'nextgen-facebook' );
_x( '[None]', 'option value', 'nextgen-facebook' );
_x( 'No', 'option value', 'nextgen-facebook' );
_x( '(no videos)', 'option value', 'nextgen-facebook' );
_x( '(option disabled)', 'option value', 'nextgen-facebook' );
_x( 'Ow.ly', 'option value', 'nextgen-facebook' );
_x( 'Pro Licenses and Extension Plugins', 'lib file description', 'nextgen-facebook' );
_x( 'Right', 'option value', 'nextgen-facebook' );
_x( 'Saturday', 'option value', 'nextgen-facebook' );
_x( '(settings value)', 'option value', 'nextgen-facebook' );
_x( 'Sharing Buttons', 'lib file description', 'nextgen-facebook' );
_x( 'Sharing Styles', 'lib file description', 'nextgen-facebook' );
_x( 'Shortcode', 'metabox tab', 'nextgen-facebook' );
_x( 'Social and SEO Image Dimensions', 'lib file description', 'nextgen-facebook' );
_x( 'Sunday', 'option value', 'nextgen-facebook' );
_x( 'Thursday', 'option value', 'nextgen-facebook' );
_x( 'TinyURL (slow)', 'option value', 'nextgen-facebook' );
_x( 'Title and Excerpt', 'option value', 'nextgen-facebook' );
_x( 'Title Only', 'option value', 'nextgen-facebook' );
_x( 'Top and Bottom', 'option value', 'nextgen-facebook' );
_x( 'Top', 'option value', 'nextgen-facebook' );
_x( 'Tuesday', 'option value', 'nextgen-facebook' );
_x( 'Update Manager for the NextGEN Facebook (NGFB) Pro plugin and its Pro extensions.', 'plugin description', 'nextgen-facebook' );
_x( 'User Profile Contact Methods', 'lib file description', 'nextgen-facebook' );
_x( 'Website Social Pages and Accounts', 'lib file description', 'nextgen-facebook' );
_x( 'Wednesday', 'option value', 'nextgen-facebook' );
_x( 'Widget', 'metabox tab', 'nextgen-facebook' );
_x( 'Yes', 'option value', 'nextgen-facebook' );
_x( 'Your Social Settings', 'lib file description', 'nextgen-facebook' );
?>
